// Authentication

export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const SET_ACTIVE_USER = "SET_ACTIVE_USER";

// profile actions

export const SET_VIEWED_PROFILE = "SET_VIEWED_PROFILE";
export const SET_VIEWED_USER_SAYS = "SET_VIEWED_USER_SAYS";

// app interaction

export const IS_LOGGING_IN = "IS_LOGGING_IN";
export const IS_CREATING_ACCOUNT = "IS_CREATING_ACCOUNT";
export const IS_GETTING_PROFILE_DETAILS = "IS_GETTING_PROFILE_DETAILS";
export const IS_GETTING_SAYS = "IS_GETTING_SAYS";
export const IS_VERIFYING_AUTHENTICATION = "IS_VERIFYING_AUTHENTICATION";
